version: '3'

services:
  # PHP Service
  app:
    build:
      context: ..
      dockerfile: ../Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    ports:
        -   9000:9000
    env_file:
        - ../.env
    networks:
      - ets_network

networks:
    ets_network:
        external: true

