version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel11-app
    env_file:
        - .env
    ports:
      - "9000:9000"  # Maps container port 80 to host port 80
    volumes:
      - .:/var/www/html
    networks:
      - ets_network

  nginx:
    image: nginx:latest
    container_name: nginx-laravel
    ports:
        - "80:80"
    volumes:
        - ./nginx/ets.conf:/etc/nginx/conf.d/default.conf
        - .:/var/www/html
    networks:
        - ets_network
    depends_on:
        - app

networks:
    ets_network:
        external: true
