version: "3.8"
services:
    db:
      image: mysql:8.0
      container_name: laravel_db
      restart: unless-stopped
      command: mysqld --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: laravel
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: secret
        MYSQL_USER: laravel
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
        
      ports:
        - "3307:3306"