version: "3.8"
services:
    mysql:
        image: mysql:latest
        container_name: laravel_mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: G7t#r9Xz!Kw2L@mq
        networks:
            - ets_network
networks:
    ets_network:
        external: true
